# Generated by Django 5.2.4 on 2025-11-13 16:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import restaurants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=restaurants.models.default_locales,
                        help_text="Category name in multiple languages, e.g. {'en': 'Starters', 'fr': 'Entrées'}",
                    ),
                ),
            ],
            options={
                "verbose_name": "DishCategory",
                "verbose_name_plural": "DishCategories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=restaurants.models.default_locales,
                        help_text="Option name in multiple languages, e.g. {'en': 'Extra Rice', 'fr': 'Riz supplémentaire'}",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=restaurants.models.default_locales,
                        help_text="Option description in multiple languages",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": ["restaurant", "name"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=restaurants.models.default_locales,
                        help_text="Restaurant name in multiple languages, e.g. {'en': 'Bistro', 'fr': 'Bistro'}",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Identifier in the URL or the QR code",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=300)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="restaurant_logos/DEFAULTLOGO.jpg",
                        help_text="Upload a square PNG or JPG logo",
                        null=True,
                        upload_to="restaurant_logos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Owner or manager if True; regular staff if False",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which restaurant this user works at",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_users",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=restaurants.models.default_locales,
                        help_text="Dish name in multiple languages, e.g. {'en': 'Caesar Salad', 'fr': 'Salade César'}",
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=restaurants.models.default_locales,
                        help_text="Dish description in multiple languages",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional picture of the dish",
                        null=True,
                        upload_to="dish_images/",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="restaurants.dishcategory",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select zero or more extra options",
                        related_name="dishes",
                        to="restaurants.option",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("placed", "Placed"),
                            ("preparing", "Preparing"),
                            ("served", "Served"),
                            ("cancelled", "Cancelled"),
                            ("paid", "Paid"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra order metadata (payment id, notes, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField(default=restaurants.models.default_locales)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants.dish",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True, related_name="order_items", to="restaurants.option"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurants.order",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="option",
            name="restaurant",
            field=models.ForeignKey(
                help_text="Which restaurant this option belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="dishcategory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_categories",
                to="restaurants.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(
                        help_text="The human‑visible table number (e.g. 1, 2, 3…)"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Opaque token used in the URL",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["restaurant", "table_number"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="restaurants.table",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=restaurants.models.default_locales,
                        help_text="Tag name in multiple languages, e.g. {'en': 'Spicy', 'fr': 'Épicé'}",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("restaurant", "name")},
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select zero or more tags",
                related_name="dishes",
                to="restaurants.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="option",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dishcategory",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dish",
            unique_together={("category", "name")},
        ),
    ]
