# Generated by Django 5.2.4 on 2025-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a square PNG or JPG logo",
                null=True,
                upload_to="restaurant_logos/",
            ),
        ),
    ]
