# Generated by Django 5.2.8 on 2025-12-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="options",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot of options chosen at order time",
            ),
        ),
    ]
